### ISSUE TITLE
محاسبه قمری

### ISSUE THREAD

**Issue by alishefaee** [pasoonate/pasoonate-js#4]
با سلام
تاریخ قمری  یک روز جلو محاسبه میشود
![Capture](https://user-images.githubusercontent.com/47412484/131158444-90eeb54a-ee98-42e1-8446-48c662388d44.JPG)
![Capture1](https://user-images.githubusercontent.com/47412484/131158473-219a398a-8530-41eb-8f3d-79d6e64d6505.JPG)

**Comment by ataiemajid63** [comment]
سلام، جدیدا مشکل تاریخ قمری شیعه حل شده ولی نسخه جدید منتشر نشده. به زودی
نسخه جدید منتشر می‌شه و اطلاع می‌دم که به روز رسانی کنید.

**Comment by ataiemajid63** [comment]
نسخه 1.0.0 کتابخانه منتشر شد و مشکل محاسبه تقویم قمری شیعه برطرف شده است.
@shafaprince
